version: "3.8"

services:
  lightroom-api:
    image: ghcr.io/pppontusw/simple-lightroom-analytics-api:latest
    ports:
      - "8089:8000"
    environment:
      - API_KEY=changeme
      - LR_CATALOG_FILE=/catalog/catalog-v13-3.lrcat
    volumes:
      - /volume2/simple-lightroom-analytics-api/catalog:/catalog:rw
    restart: unless-stopped
